# Header
menu:
  Home: /
  Archives: /archives
  Github: https://github.com/XKXDA
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /fav-48.png
